export const FETCH_USER = 'fetch_user'
export const GET_DEFAULT_BOOK_PROGRESS = 'default_book_progress'
export const UPLOAD_STATUS = 'BOOK_UPLOAD'
export const BOOK_PROGRESS = 'book_progress'
export const GET_BOOK_CONTENTS = 'book_contents'
export const PROCESS_SPEECH_DATA = 'speech_data_update'
